version: "3.8"
services:
  netboard:
    # image: k8ie/netboard
    build: .
    # restart: unless-stopped
    volumes:
      - /home/k8ie/test:/usr/local/apache2/htdocs/storage
    ports:
      - 8080:80
